import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { NgxSpinnerService } from 'ngx-spinner';
import { NotifierService } from 'src/app/shared/services/notifier.service';
import { AdminService } from '../../admin.service';
import { DatePipe } from "@angular/common";
import { User } from "src/app/shared/models/user";
declare var $: any;
@Component({
  selector: 'app-mrp-past-data',
  templateUrl: './mrp-past-data.component.html',
  styleUrls: ['./mrp-past-data.component.scss']
})
export class MrpPastDataComponent implements OnInit {
  context: any;
  gridOptions: any;
  headerHeight: number;
  rowHeight: number;
  rowSelection: string;
  gridApi: any;
  gridColumnApi: any;
  MRPName: any;
  frameworkComponents: any;
  Month: any;
  revision: any;
  plantName: any;
  rowGroupPanelShow: string;
  rowData: any;
  Status: any;
  selectedStatus: any
  zoneCode: any;
  zoneCodes: any;
  formData: FormData;
  uploadForm: any;
  filename1: string;
  isCSV: boolean;
  isFileSelected = true;
  mrpName: any;
  pageSize: number;
  paginationPageSize: number;
  MrpData = [];
  selectedBuyer: any;
  selectedYear: any;
  minDate: Date;
  updatedDate: Date;
  fileList: any[];
  mrpViewClicked: boolean;
  currentUser: User;
  months = [
    "",
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];
  monthList = [
    "",
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "June",
    "July",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];

  MrpListColumnDef = [
    {
      headerName: "Month",
      field: "monthName",
      filter: "agTextColumnFilter",
      headerTooltip: "Month",
      width: 200,
      editable: false,
      enableRowGroup: true,
      headerClass: 'text-center',
    },
    {
      headerName: "Upload Date",
      field: "Date",
      filter: false,
      headerTooltip: "Upload Date ",
      width: 200,
      editable: false,
      headerClass: 'text-center',
      enableRowGroup: true,
      cellStyle: {
        textAlign: 'center'
      },
      valueFormatter: (params) => {
        if (params.value !== undefined) {
          const date = new Date(params.value);
          const datepipe: DatePipe = new DatePipe("en-US");
          return datepipe.transform(date, "dd/MM/yyyy");
        }
      },
    },
    {
      headerName: "Revision",
      field: "Revision",
      filter: false,
      headerTooltip: "Revision",
      width: 200,
      editable: false,
      enableRowGroup: true,
      headerClass: 'text-center',
      cellStyle: {
        textAlign: 'right'
      },
    },
    {
      headerName: "Action",
      field: "id",
      filter: false,
      headerClass: 'text-center',
      // headerTooltip: "Generated By",
      cellRenderer: function (params) {
        if (
          params !== null &&
          params !== undefined &&
          params.data !== undefined &&
          params.data !== null
        ) {
          return '<a class="padding-left-20 c-pointer"> <i class="fa fa-eye" aria-hidden="true" ></i></a>';
        }
      },
      width: 100,
      editable: false,
    },
  ]

  columnDefs = [];
 
  defaultColDef = {
    sortable: true,
    resizable: true,
    headerClass: 'grid-cell-centered'
  };
  MrpListdefaultColDef = {
    sortable: true,
    resizable: true,
    headerClass: 'grid-cell-centered'
  };
  buyerlist: any;
  uploadedDate: Date;
  plantList: any;
  isxlsx: boolean;
  mrpImport: any;
  importgridApi: any;
  importgridColumnApi: any;
  importdefaultColDef: any;
  fileUploadedList: any;
  MrpgridApi: any;
  MrpgridColumnApi: any;
  MrpListData: any;

  onGridReady(params) {
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;
  }

  onMrpListGridReady(params) {
    this.MrpgridApi = params.api;
    this.MrpgridColumnApi = params.columnApi;
  }
  onImportGridReady(params) {
    this.importgridApi = params.api;
    this.importgridColumnApi = params.columnApi;
    this.importgridApi.sizeColumnsToFit();
  }

  constructor(
    private adminService: AdminService,
    private spinner: NgxSpinnerService,
    private http: HttpClient,
    private notifier: NotifierService
  ) {
    this.context = { componentParent: this };
    this.gridOptions = {
      context: {
        componentParent: this,
      },
    }
    const gridSize = 6;
    this.fileUploadedList = [];
    this.rowHeight = gridSize * 4;
    this.headerHeight = gridSize * 4;
    this.rowSelection = "multiple";
    this.rowGroupPanelShow = "always";
    this.mrpViewClicked = false;
    this.selectedYear = new Date()
    this.minDate = new Date();
    this.pageSize = 1;
    this.updatedDate = new Date;
    this.fileList = new Array<any>();

    this.importdefaultColDef = {
      sortable: true,
      filter: true,
      resizable: true,
    };

    this.MrpListData = [];
    this.currentUser = JSON.parse(sessionStorage.getItem('ActiveUser'));
  }

  ngOnInit(): void {
    this.getPlantList();
    this.getFileUploadedDetails();
    this.getMRPList();
  }

  getMRPList() {
    this.spinner.show();
    let data
    if (this.currentUser !== null &&
      this.currentUser !== undefined &&
      this.currentUser.RoleCode !== null &&
      this.currentUser.RoleCode !== undefined &&
      (this.currentUser.RoleCode === "Admin" ||
        this.currentUser.RoleCode === "admin")) {
      data = {
        BuyerCode: ""
      }
    }
    else{
      data = {
        BuyerCode: this.currentUser.EmployeeCode
      }
    }
    // this.http.get<any>("http://localhost:3000/MRPList").subscribe(res => {
    this.adminService.getMrpList(data).subscribe(res => {
      if (res.Message) {
        //this.notifier.notify(res.Message, 1);
        this.MrpListData = [];
        this.spinner.hide();
      }
      else
        if (res && !res.message) {
          let mrpList=res.Result.Table;
          const date = new Date().getMonth()+1;
          const year=  new Date().getFullYear();
          // const date1 = new Date().getMonth();
          let mrp=[];
          mrpList.forEach((data)=>{
            if(data.year < year){
              data.monthName=this.months[(data.Month)]
              mrp.push(data);
            }
            if( data.year >= year && data.Month < date ){
              data.monthName=this.months[(data.Month)]
              mrp.push(data);
            } 
          })
          this.MrpListData=mrp;
          mrp=[];
          this.spinner.hide();
        }
        else {
          this.spinner.hide();
        }
    },
      (err) => {
        this.spinner.hide();
        //  this.notifier.notify(err.message, 4);
      })
  }
  onOpenYearCalendar(container) {
    container.yearSelectHandler = (event: any): void => {
      container._store.dispatch(container._actions.select(event.date));
    };
    container.setViewMode("year");
  }

  resetData() {

  }
  getData() {
    // this.router.navigate(["/key-data"]);
    this.uploadedDate = new Date();
    $(".invoice, .common-bg").show();
    document.getElementById('last-updated-mrp-data').style.display = 'block';
  }

  closeModal() {
    $(".invoice, .common-bg").hide();
    document.getElementById('last-updated-mrp-data').style.display = 'none';
  }
  getPlantList() {
    this.spinner.show();

    this.adminService.getPlantList().subscribe(
      (res) => {
        // this.http.get<any>("http://localhost:3000/plantLocation").subscribe(res => {

        if (res) {
          this.spinner.hide();
          this.plantList = res.Result;

        } else {
          this.spinner.hide();
        }
      },
      (err) => {
        this.spinner.hide();
        this.notifier.notify(err.message, 4);
      }
    );
  }

  getFileUploadedDetails() {
    this.adminService.getFileUploadedDate().subscribe(
      (res) => {
        if (res) {
          this.fileUploadedList = res.Result.Result;
        }
      })
  }

  getMRPDetails() {
    this.spinner.show();
    let date = new Date();
    const data = {
      PageCriteria: {
        PageNumberToFetch: 1,
        PageSize: 100
      },
      BuyerID: this.selectedBuyer,
      StartMonth: date.getMonth() + 1,
      StartYear: date.getFullYear()
    };
    this.adminService.getMrpDetails(data).subscribe(
      (res) => {
        if (res) {
          if (res.message || res.Message) {
            this.MrpData = [];
            this.notifier.notify(res.message, 1);
            this.spinner.hide();
          }
          else {
            this.MrpData = res;
            this.columnDefs = MRPColumnDefs();
            let dateList = [];
            let date = new Date();
            const datepipe: DatePipe = new DatePipe("en-US");
            let start_date = datepipe.transform(new Date(), "dd/MM/yyyy");
            const start = start_date.split("/");
            let endYear;
            let endMonth
            let startYear = start[2];
            let startMonth = start[1];
            if (start[1] === "01") {
              endMonth = 12
              endYear = +startYear;
            }
            else if (start[1] === "12") {
              endMonth = 11
              endYear = +startYear + 1;
            }
            else {
              endYear = +startYear + 1;
              endMonth = +startMonth - 1;
            }
            dateList = dateRange(formatDate(new Date(+startYear, +start[1], +start[0])), formatDate(new Date(endYear, endMonth, +start[0])));

            if (this.columnDefs !== null &&
              this.columnDefs !== undefined) {
              if (this.plantList !== null &&
                this.plantList !== undefined &&
                this.plantList.length > 0) {
                this.plantList.forEach((colDef) => {

                  let plantName = colDef.PlantCode + "-" + colDef.PlantName
                  const column = {
                    headerName: plantName,
                    headerClass: 'grid-cell-centered ',
                    children: [
                    ]
                  }

                  dateList.forEach((element) => {
                    const elementArr = element.split("-");
                    let key = null;
                    // const yearCount = new Date(elementArr[0], elementArr[1], 1).toLocaleDateString('en', {year: '2-digit'})
                    const yearCount = elementArr[0].substring(2, 4);
                    // key =this.months[+elementArr[1]]+ "_" +yearCount;
                    const col = {
                      headerName: this.monthList[+elementArr[1]] + "-" + yearCount,
                      // field:plantName,
                      field: colDef.PlantCode + "_" + this.months[+elementArr[1]] + "_" + yearCount,
                      //   field: colDef.PlantCode + "_" + this.months[+elementArr[1]] + "_" + yearCount,
                      width: 100,
                      suppressSizeToFit: true,
                      headerClass: 'text-center',
                      cellStyle: {
                        textAlign: 'center'
                      },
                      // cellStyle: {
                      //   textAlign: 'center',
                      //   headerClass: 'grid-cell-centered ',
                      // },
                      valueFormatter: dollerFormatter,
                    };
                    column.children.push(col)

                  });

                  this.columnDefs.push(column);
                })
              }
            }
            this.spinner.hide();
          }
        }
        else {
          this.MrpData = [];
          this.spinner.hide();
        }
      },
      (err) => {
        this.spinner.hide();
        this.notifier.notify(err.message, 4);
      }
    );
  }
 
  onCellClicked(event) {
    if (event !== null &&
      event !== undefined &&
      event.colDef !== null &&
      event.colDef !== undefined &&
      event.colDef.headerName !== null &&
      event.colDef.headerName !== undefined &&
      event.colDef.headerName === "Action") {
      this.mrpViewClicked = true;
      const data = {
        PageCriteria: {
          PageNumberToFetch: 1,
          PageSize: 100
        },
        Revision: event.data.Revision,
        StartMonth: event.data.Month,
        StartYear: event.data.year
      }
      this.spinner.show();
      this.adminService.getMrpDetailData(data).subscribe(
        (res) => {
          if (res) {
            if (res.message || res.Message) {
              this.MrpData = [];
              this.notifier.notify(res.message, 1);
              this.spinner.hide();
            }
            else {
              this.MrpData = res;
              this.columnDefs = MRPColumnDefs();
              let dateList = [];
              let date = new Date();
              const datepipe: DatePipe = new DatePipe("en-US");
              let start_date = datepipe.transform(new Date(), "dd/MM/yyyy");
              const start = start_date.split("/");
              let endYear;
              let endMonth
              let startYear = start[2];
              let startMonth = start[1];
              if (start[1] === "01") {
                endMonth = 12
                endYear = +startYear;
              }
              else if (start[1] === "12") {
                endMonth = 11
                endYear = +startYear + 1;
              }
              else {
                endYear = +startYear + 1;
                endMonth = +startMonth - 1;
              }
              dateList = dateRange(formatDate(new Date(+startYear, +start[1], +start[0])), formatDate(new Date(endYear, endMonth, +start[0])));

              if (this.columnDefs !== null &&
                this.columnDefs !== undefined) {
                if (this.plantList !== null &&
                  this.plantList !== undefined &&
                  this.plantList.length > 0) {
                  this.plantList.forEach((colDef) => {

                    let plantName = colDef.PlantCode + "-" + colDef.PlantName
                    const column = {
                      headerName: plantName,
                      // headerClass: (params) => {
                      //   for (let i = 0; i <= this.plantList.length; i++) {
                      //     let list=params.colDef.headerName.split("-");
                      //     if(this.plantList[i].PlantCode ===list[0] ){
                      //       if(i %2 ===0){
                      //         return "rag-2002"
                      //       }
                      //       else{
                      //         return "rag-2007"
                      //       }
                      //     }
                      //   }
                      // },
                      headerClass: (params) => {
                        if (params !== null &&
                          params !== undefined &&
                          params.colDef !== null &&
                          params.colDef !== undefined

                        ) {
                          if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2001")
                          ) {
                            return "rag-2001"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2002")
                          ) {
                            return "rag-2002"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2003")
                          ) {
                            return "rag-2003"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2004")
                          ) {
                            return "rag-2004"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2005")
                          ) {
                            return "rag-2005"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2006")
                          ) {
                            return "rag-2006"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2007")
                          ) {
                            return "rag-2007"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2009")
                          ) {
                            return "rag-2009"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2010")
                          ) {
                            return "rag-2010"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2012")
                          ) {
                            return "rag-2012"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2015")
                          ) {
                            return "rag-2015"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2018")
                          ) {
                            return "rag-2018"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2019")
                          ) {
                            return "rag-2019"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2022")
                          ) {
                            return "rag-2022"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2025")
                          ) {
                            return "rag-2025"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2051")
                          ) {
                            return "rag-2051"
                          }
                          else if (
                            params.colDef.headerName !== null &&
                            params.colDef.headerName !== undefined &&
                            params.colDef.headerName.includes("2053")
                          ) {
                            return "rag-2053"
                          }
                          else{
                            return "rag-any"
                          }
                        }
                      },
                      children: [
                      ]
                    }

                    dateList.forEach((element) => {
                      const elementArr = element.split("-");
                      let key = null;
                      // const yearCount = new Date(elementArr[0], elementArr[1], 1).toLocaleDateString('en', {year: '2-digit'})
                      const yearCount = elementArr[0].substring(2, 4);
                      // key =this.months[+elementArr[1]]+ "_" +yearCount;
                      const col = {
                        headerName: this.monthList[+elementArr[1]] + "-" + yearCount,
                        // field:plantName,
                        field: colDef.PlantCode + "_" + this.months[+elementArr[1]] + "_" + yearCount,
                        //   field: colDef.PlantCode + "_" + this.months[+elementArr[1]] + "_" + yearCount,
                        width: 100,
                        suppressSizeToFit: true,
                        // headerClass: (params) => {
                        //   for (let i = 0; i <= this.plantList.length; i++) {
                        //     let list=params.colDef.field.split("_");
                        //     if(this.plantList[i].PlantCode ===list[0] ){
                        //       if(i %2 ===0){
                        //         return "rag-2002"
                        //       }
                        //       else{
                        //         return "rag-2007"
                        //       }
                        //     }
                           
                        //   }
                        // },
                         //   headerClass: 'text-center',
                        headerClass: (params) => {
                          if (params !== null &&
                            params !== undefined &&
                            params.colDef !== null &&
                            params.colDef !== undefined

                          ) {
                            if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2001")
                            ) {
                              return "rag-2001"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2002")
                            ) {
                              return "rag-2002"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2003")
                            ) {
                              return "rag-2003"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2004")
                            ) {
                              return "rag-2004"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2005")
                            ) {
                              return "rag-2005"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2006")
                            ) {
                              return "rag-2006"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2007")
                            ) {
                              return "rag-2007"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2009")
                            ) {
                              return "rag-2009"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2010")
                            ) {
                              return "rag-2010"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2012")
                            ) {
                              return "rag-2012"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2015")
                            ) {
                              return "rag-2015"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2018")
                            ) {
                              return "rag-2018"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2019")
                            ) {
                              return "rag-2019"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2022")
                            ) {
                              return "rag-2022"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2025")
                            ) {
                              return "rag-2025"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2051")
                            ) {
                              return "rag-2051"
                            }
                            else if (
                              params.colDef.field !== null &&
                              params.colDef.field !== undefined &&
                              params.colDef.field.includes("2053")
                            ) {
                              return "rag-2053"
                            }
                            else {
                              return "rag-any"
                            }
                          }
                        },
                        cellStyle: {
                          textAlign: 'right'
                        },
                        // cellStyle: {
                        //   textAlign: 'center',
                        //   headerClass: 'grid-cell-centered ',
                        // },
                        valueFormatter: dollerFormatter,
                      };
                      column.children.push(col)

                    });

                    this.columnDefs.push(column);

                  })
                  
                  // const totalColumn = {
                  //   headerName: "Total",
                  //   headerClass :(params)=>{
                  //     console.log(params)
                  //     if(params !== null &&
                  //       params !== undefined &&
                  //       params.colDef !==  null && 
                  //       params.colDef !== undefined &&
                  //       params.colDef.headerName !== null &&
                  //       params.colDef.headerName !== undefined &&
                  //       params.colDef.headerName === "Total"
                  //       ){
                  //         return "rag-2053"
                  //       }
                  //   },
                  //   children:[]     
                  // }

                  // dateList.forEach((element)=>{
                  //   const elementArr = element.split("-");
                  //   let key = null;
                  //   // const yearCount = new Date(elementArr[0], elementArr[1], 1).toLocaleDateString('en', {year: '2-digit'})
                  //   const yearCount = elementArr[0].substring(2, 4);
                  //   // key =this.months[+elementArr[1]]+ "_" +yearCount;
                  //   const col = {
                  //     headerName: this.monthList[+elementArr[1]],
                  //     // field:plantName,
                  //     field: "_" + this.months[+elementArr[1]] + "_" + yearCount,
                  //     //   field: colDef.PlantCode + "_" + this.months[+elementArr[1]] + "_" + yearCount,
                  //     width: 100,
                  //     suppressSizeToFit: true,
                  //     // headerClass: 'text-center',
                  //     headerClass :(params)=>{
                  //       console.log(params)
                  //       if(params !== null &&
                  //         params !== undefined &&
                  //         params.colDef !==  null && 
                  //         params.colDef !== undefined 
                  //         // &&
                  //         // params.colDef.headerName !== null &&
                  //         // params.colDef.headerName !== undefined &&
                  //         // (params.colDef.headerName === "Jan" ||
                  //         // params.colDef.headerName === "Feb" ||
                  //         // params.colDef.headerName === "Mar" ||
                  //         // params.colDef.headerName === "Apr" ||
                  //         // params.colDef.headerName === "May" ||
                  //         // params.colDef.headerName === "June" || 
                  //         // params.colDef.headerName === "July" ||
                  //         // params.colDef.headerName === "Aug" ||
                  //         // params.colDef.headerName === "Sep"||
                  //         // params.colDef.headerName === "Oct" ||
                  //         // params.colDef.headerName === "Nov" ||
                  //         // params.colDef.headerName === "Dec")
                  //         ){
                  //           return "rag-2053"
                  //         }
                  //     },
                  //   };
                  //   totalColumn.children.push(col)
                  // })
                  // this.columnDefs.push(totalColumn);
                }
              }
              this.spinner.hide();
            }
          }
          else {
            this.notifier.notify("Data Not Found", 1);
            this.spinner.hide()
          }
        },
        (err) => {
          this.MrpData = [];
          this.notifier.notify("Data Not Found", 1);
          this.spinner.hide();
          //this.notifier.notify(err.message, 4);
        })


    }
  }

}

function dateRange(startDate, endDate) {
  const start = startDate.split("-");
  const end = endDate.split("-");
  let startMonth = start[1];
  let startYear = parseInt(start[0]);
  const endYear = parseInt(end[0]);
  if (start[1] === '00') {
    startMonth = '12';
    startYear = parseInt(start[0]) - 1;
  }

  const dates = [];
  for (let i = startYear; i <= endYear; i++) {
    const endMonth = i !== endYear ? 11 : parseInt(end[1]) - 1;
    const startMon = i === startYear ? parseInt(startMonth) - 1 : 0;
    for (let j = startMon; j <= endMonth; j = j > 12 ? j % 12 || 11 : j + 1) {
      const month = j + 1;
      const displayMonth = month < 10 ? "0" + month : month;
      dates.push([i, displayMonth, "01"].join("-"));
    }
  }
  return dates;
}

function MRPColumnDefs() {
  return [
    // {
    //   headerName: "Date",
    //   field: "date",
    //   filter: false,
    //   headerTooltip: "Date",
    //   width: 100,
    //   editable: false,
    //   headerClass: 'text-center',
    // },
    {
      headerName: "Item Code",
      field: "ItemCode",
      filter: "agTextColumnFilter",
      headerTooltip: "Item Code",
      width: 130,
      editable: false,
      headerClass: 'text-center',
      cellStyle: {
        textAlign: 'right'
      },
    },
    {
      headerName: "Item Description",
      field: "Description",
      filter: false,
      headerTooltip: "Item Code",
      width: 200,
      editable: false,
      headerClass: 'text-center',
    },
    {
      headerName: "Supplier Code",
      field: "SupplierCode",
      filter: "agTextColumnFilter",
      headerTooltip: "Supplier Code",
      width: 150,
      editable: false,
      headerClass: 'text-center',
      cellStyle: {
        textAlign: 'right'
      },
    },
    {
      headerName: "Supplier Name",
      field: "SupplierName",
      filter: "agTextColumnFilter",
      headerTooltip: "Supplier Name",
      width: 150,
      editable: false,
      headerClass: 'text-center',

    },
    {
      headerName: "Buyer Code",
      field: "BuyerCode",
      filter: "agTextColumnFilter",
      headerTooltip: "Buyer Code",
      width: 150,
      editable: false,
      headerClass: 'text-center',
      // cellStyle: {
      //   textAlign: 'right'
      // },
    },
    {
      headerName: "Buyer Name",
      field: "BuyerName",
      filter: "agTextColumnFilter",
      headerTooltip: "Buyer Name",
      width: 150,
      editable: false,
      headerClass: 'text-center',
    },
    {
      headerName: "Map",
      field: "Map",
      filter: "agTextColumnFilter",
      headerTooltip: " Map",
      width: 150,
      editable: false,
      headerClass: 'text-center',
    },
    {
      headerName: "Unit",
      field: "Unit",
      filter: "agTextColumnFilter",
      headerTooltip: " Unit",
      width: 100,
      editable: false,
      headerClass: 'text-center',
    },
    {
      headerName: "Customer",
      field: "Customer",
      // filter: "agTextColumnFilter",
      headerTooltip: " Customer",
      width: 200,
      editable: false,
      headerClass: 'text-center',
    },
    {
      headerName: "Project",
      field: "Project",
      filter: "agTextColumnFilter",
      headerTooltip: "Project",
      width: 200,
      editable: false,
    },

  ]

}


function formatDate(date) {
  const d = new Date(date);
  let month = "" + (d.getMonth());
  let day = "" + d.getDate();
  const year = d.getFullYear();
  if (month.length < 2) {
    month = "0" + month;
  }
  if (day.length < 2) {
    day = "0" + day;
  }
  return [year, month, day].join("-");
}

function dollerFormatter(params) {
  if (params.value === undefined || null) {
    return params.value = "0.00";
  } else {
    if (params.value < 0) {
  //    return "(" + formatNumber(params.value * -1) + ")";
    } else {
  //    return "" + formatNumber(params.value);
    }
  }
}

function formatNumber(num: number) {
  if (num % 1 !== 0) {
    return Number(num)
      .toFixed(2)
      .toString()
      .replace(/(\d)(?=(\d{3})+(?!\d))/g, "1,");
  } else {
    return Number(num)
      .toFixed(2)
      .toString()
      .replace(/(\d)(?=(\d{3})+(?!\d))/g, "1,");
  }
}
